name: Python calculator application

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run calculator script
        run: |
          python mathamatic.py

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run pytest
        run: |
          pytest test.py

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up deployment
        run: |
          echo "Setting up deployment..."

      - name: Deploy to production
        run: |
          echo "Deploying to production..."

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pylint

      - name: Run pylint test file
        run: |
          pylint test.py 
          
      - name: Run pylint mathamatic file
        run: |   
          pylint mathamatic.py     
