name: Python calculator application

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pytest

      - name: Run Python calculator
        run: |
          python mathamatic.py
      - name: Run pylint test file
        run: |
          pylint --disable=W mathamatic.py
      - name: Run PYTEST
        run: |
          pytest test.py
      